hpc<-read.table(".\\household_power_consumption.txt",sep=";",quote = "\"",dec = ".",header=TRUE,stringsAsFactors=FALSE)
hpc$Date<-as.Date(hpc$Date,format="%d/%m/%Y")
a<-subset(hpc,Date=="2007-2-1")
b<-subset(hpc,Date=="2007-2-2")
x<-rbind(a,b)
x[,3]<-as.numeric(x[,3])
z<-paste(x[,1],x[,2])
z<-strptime(z,format="%Y-%m-%d %H:%M:%S")
png(file="plot2.png",width=480,height=480)
plot(z,x[,3],type="s",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()