hpc<-read.table(".\\household_power_consumption.txt",sep=";",quote = "\"",dec = ".",header=TRUE,stringsAsFactors=FALSE)
hpc$Date<-as.Date(hpc$Date,format="%d/%m/%Y")
a<-subset(hpc,Date=="2007-2-1")
b<-subset(hpc,Date=="2007-2-2")
x<-rbind(a,b)
x[,7]<-as.numeric(x[,7])
x[,8]<-as.numeric(x[,8])
x[,9]<-as.numeric(x[,9])
z<-paste(x[,1],x[,2])
z<-strptime(z,format="%Y-%m-%d %H:%M:%S")
png(file="plot3.png",width=480,height=480)
plot(z,x[,7],type="s",ylab="Energy sub metering",col="black")
lines(z,x[,8],type="s",col="red")
lines(z,x[,9],type="s",col="blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch="",col=c("black","red","blue"),lwd=1)
dev.off()