hpc<-read.table(".\\household_power_consumption.txt",sep=";",quote = "\"",dec = ".",header=TRUE,stringsAsFactors=FALSE)
hpc$Date<-as.Date(hpc$Date,format="%d/%m/%Y")
a<-subset(hpc,Date=="2007-2-1")
b<-subset(hpc,Date=="2007-2-2")
x<-rbind(a,b)
x[,3]<-as.numeric(x[,3])
png(file="plot1.png",width=480,height=480)
hist(x[,3],col='red',xlab='Global Active Power (kilowatts)',main='Global Active Power')
dev.off()